name: Allure Report Deployment

on:
  push:
    branches:
      - main  # Change as needed

jobs:
  test-job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Tests with Allure
        run: |
          pytest --alluredir=allure-results

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-job1
          path: allure-results

  test-job-2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Tests with Allure
        run: |
          pytest --alluredir=allure-results

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-job2
          path: allure-results

  generate-and-deploy:
    needs: [test-job-1, test-job-2]
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for GitHub Pages deployment

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Allure Results from Job 1
        uses: actions/download-artifact@v4
        with:
          name: allure-results-job1
          path: merged-allure-results

      - name: Download Allure Results from Job 2
        uses: actions/download-artifact@v4
        with:
          name: allure-results-job2
          path: merged-allure-results

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@v1
        with:
          results-dir: merged-allure-results
          report-dir: allure-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
          publish_branch: gh-pages
          force_orphan: true  # Clears old files to prevent conflicts
